name: Ktlint
on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - main

jobs:
  ktlint:
    name: Check Code Quality
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@main
        with:
          fetch-depth: 1

      - name: ktlint
        uses: ScaCap/action-ktlint@master
        with:
          github_token: ${{ secrets.PRIVATE_TOKEN }}
          reporter: github-pr-review
          android: false
          fail_on_error: true
          level: warning
          ktlint_version: 0.41.0