name: Deploy to prod env
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.PRIVATE_TOKEN }}
          submodules: true

      - name: create remote directory
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_KNOWN_HOSTS }}
          username: ubuntu
          key: ${{ secrets.SSH_PEM_KEY }}
          script: mkdir -p /home/ubuntu/backend

      - name: copy source via ssh key
        uses: burnett01/rsync-deployments@4.1
        with:
          switches: -avzr --delete
          remote_path: /home/ubuntu/backend
          remote_host: ${{ secrets.SSH_KNOWN_HOSTS }}
          remote_user: ubuntu
          remote_key: ${{ secrets.SSH_PEM_KEY }}

      - name: trigger script
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_KNOWN_HOSTS }}
          username: ubuntu
          key: ${{ secrets.SSH_PEM_KEY }}
          script: sh /home/ubuntu/backend/deploy.sh


      #- name: slack-notification
      #  uses: 8398a7/action-slack@v3
      #  with:
      #    status: ${{ job.status }}
      #    author_name: Github Action Test # default: 8398a7@action-slack
      #    fields: repo,message,commit,author,action,eventName,ref,workflow,job,took
      #  env:
      #    SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # required
      #  if: always() # Pick up events even if the job fails or is canceled.
